name: test-standard-install

on:
  push:
    paths:
      - '.github/workflows/test-standard-install.yml'
      - 'standard_setup/vm_soft_setup.sh'

jobs:
  test-standard-install:
    name: Test standard installation script.
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installation
        run: bash standard_setup/vm_soft_setup.sh
